server:
  http:
    addr: 0.0.0.0:8998
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8999
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/check_in_system?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    db: 8
    passWord: ""
    read_timeout: 2s
    write_timeout: 2s
